# Generated by Django 4.2.2 on 2023-08-02 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogLike', to='pages.blog')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernameLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogComment', to='pages.blog')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernameComment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
